<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wisegateEmployee</name>
   <tag></tag>
   <elementGuidId>83b7b1e4-8e6e-4378-997b-10becf61a3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wisegateEmployeeInfo.wisegateEmployee</value>
   </webElementProperties>
</WebElementEntity>
